dist: trusty
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

install:
  - composer install
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then composer require "phpunit/phpunit:4.8"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require "phpunit/phpunit:4.8"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require "phpunit/phpunit:5.7"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer require "phpunit/phpunit:5.7"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require "phpunit/phpunit:7.0"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require "phpunit/phpunit:8.0"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then composer require "phpunit/phpunit:9.5"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then composer require "phpunit/phpunit:9.5"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then composer require "phpunit/phpunit:9.5"; fi
